---
- hosts: all-servers
  roles:
    - name: common-packages
      tags: [base, common-packages]
      become: yes

    - name: network
      tags: [base, network]

    - name: docker
      tags: [base, docker]
      become: yes

- hosts: haproxy
  roles:
    - name: haproxy
      tags: [base, network, haproxy]
      become: yes

- hosts: etcd
  serial: 1
  roles:
    - name: etcd
      tags: [etcd]
      become: yes

- hosts: [master-nodes, worker-nodes]
  roles:
    - name: kubernetes
      tags: [base, kubernetes]
      become: yes

- hosts: worker-nodes
  serial: 1
  roles:
    - name: kubernetes-worker
      tags: [kubernetes, kubernetes-worker]
      become: yes
