---
- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install required Ubuntu packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - openjdk-8-jdk



