---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Installing required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: copy configuration file
  template: src=templates/k8s.conf dest="/etc/sysctl.d/k8s.conf"

- name: copy kubelet service system configuration
  template: src="kubelet.j2" dest="/etc/sysconfig/kubelet"
  notify:
    - reload systemd
    - restart kubelet

- meta: flush_handlers

- name: Starting and Enabling the kubelet
  service:
    name: kubelet
    state: started
    enabled: yes
